from pynumdiff.total_variation_regularization.__total_variation_regularization__ import velocity as velocity
from pynumdiff.total_variation_regularization.__total_variation_regularization__ import acceleration as acceleration
from pynumdiff.total_variation_regularization.__total_variation_regularization__ import jerk as jerk