"""
Import useful functions from _smooth_finite_difference
"""
from pynumdiff.smooth_finite_difference._smooth_finite_difference import mediandiff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import meandiff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import gaussiandiff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import friedrichsdiff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import butterdiff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import splinediff
from pynumdiff.smooth_finite_difference._smooth_finite_difference import __convolutional_smoother__
