"""
Import useful functions from _finite_difference module
"""
from pynumdiff.kalman_smooth._kalman_smooth import constant_velocity
from pynumdiff.kalman_smooth._kalman_smooth import constant_acceleration
from pynumdiff.kalman_smooth._kalman_smooth import constant_jerk
from pynumdiff.kalman_smooth._kalman_smooth import known_dynamics
from pynumdiff.kalman_smooth._kalman_smooth import __kalman_forward_filter__
from pynumdiff.kalman_smooth._kalman_smooth import __kalman_backward_smooth__