from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import mediandiff as mediandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import meandiff as meandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import gaussiandiff as gaussiandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import friedrichsdiff as friedrichsdiff
