"""
import useful functions from __smooth_finite_difference__
"""
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import mediandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import meandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import gaussiandiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import friedrichsdiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import butterdiff
from pynumdiff.optimize.smooth_finite_difference.__smooth_finite_difference__ import splinediff
